# Target configuration for Minecraft 26.2.x
mod.mc_title=26.2.x
mod.mc_targets=>=26.2 <26.3
mod.java_version=25
mod.release_target=true

# Fabric
dep.minecraft.fabric=26.2
dep.fabric_loader=0.19.3
dep.fabric_api_version=0.152.1+26.2

# NeoForge
dep.minecraft.neoforge=26.2
dep.minecraft_range_nf=[26.2,26.3)
dep.neoforge_loader=26.2.0.1-beta
dep.neoforge_loader_range=[2,)
dep.neoforge_version_range=[26,)
