# Compatibility-only target for Minecraft 26.1.2
mod.mc_title=26.1.x
mod.mc_targets=>=26.1 <26.2
mod.java_version=25
mod.release_target=false

# Fabric
dep.minecraft.fabric=26.1.2
dep.fabric_loader=0.18.6
dep.fabric_api_version=0.153.0+26.1.2

# NeoForge
dep.minecraft.neoforge=26.1.2
dep.minecraft_range_nf=[26.1,26.2)
dep.neoforge_loader=26.1.2.76
dep.neoforge_loader_range=[2,)
dep.neoforge_version_range=[26,)